Models/AppUser.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace smart_city_dotnetcore.Models
{
    public class AppUser
    {
        [Key]
        public int Id { get; set; }
        public required string IdentiyId { get; set; }
        [ForeignKey("UserId")]
        public Identity? Identity { get; set; }
        public required string FirstName { get; set; }
        public required string MiddleName { get; set; }
        public required string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }
        public Gender Gender { get; set; }
        public string Image { get; set; } = "";
    }
    public enum Gender {
        Male,
        Female
    }
}

Models/ElectricityBalance.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace smart_city_dotnetcore.Models
{
    public class ElectricityBalance
    {
        public int Id { get; set; }
        public int HouseId { get; set; }
        [ForeignKey("HouseId")]
        public House? House { get; set; }
        public double TotalPaidAmount { get; set; }
        public double TotalPurchasedElectricity { get; set; }
        public double TotalConsumedElectricity { get; set; }
        public double RemainingElectricity { get; set; }
        public double CurrentConsumption { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

Models/ElectricityConsumption.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace smart_city_dotnetcore.Models
{
    public class ElectricityConsumption
    {
        public int Id { get; set; }
        public int HouseId { get; set; }
        [ForeignKey("HouseId")]
        public House? House { get; set; }
        public double StartReading { get; set; }
        public double EndReading { get; set; }
        public double Consumption { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

Models/ElectricityRate.cs
namespace smart_city_dotnetcore.Models
{
    public class ElectricityRate
    {
        public int Id { get; set; }
        public required string Name { get; set; }
        public required double Value { get; set; }
        public bool Active { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

Models/ElectricityRequest.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace smart_city_dotnetcore.Models
{
    public class ElectricityRequest
    {
        public int Id { get; set; }
        public int HouseId { get; set; }
        [ForeignKey("HouseId")]
        public House? House { get; set; }
        public double DeclaredAmount { get; set; }
        public RequestStatus Status { get; set; }
        public string Image { get; set; } = "";
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }

    public enum RequestStatus {
        Pending,
        Approved,
        Rejected
    }
}

Models/ElectricityTransaction.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace smart_city_dotnetcore.Models
{
    public class ElectricityTransaction
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        [ForeignKey("RequestId")]
        public ElectricityRequest? Request { get; set; }
        public int RateId { get; set; }
        [ForeignKey("RateId")]
        public ElectricityRate? Rate { get; set; }
        public int ApproverId { get; set; }
        [ForeignKey("ApproverId")]
        public AppUser? Approver { get; set; }
        public int RemarkId { get; set; }
        public TransactionRemark? Remark { get; set; }
        public double VerifiedAmount { get; set; }
        public double ElectricityAmount { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

Models/House.cs
namespace smart_city_dotnetcore.Models
{
    public class House
    {
        public int Id { get; set; }
        public required string Name { get; set; }
        public required string Description { get; set; }
        public required string Address { get; set; }
        public required string HouseNo { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

Models/IdentityUser.cs
using Microsoft.AspNetCore.Identity;

namespace smart_city_dotnetcore.Models
{
    public class Identity : IdentityUser
    {
        
    }
}

Models/PowerMeter.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace smart_city_dotnetcore.Models
{
    public class PowerMeter
    {
        [Key]
        public int Id{ get; set; }
        public int HouseId { get; set; }
        [ForeignKey("HouseId")]
        public House? House{ get; set; }
        public required string Name { get; set; }
        public required string EntityId { get; set; }
        public required string Type { get; set; }
        public required string Phase { get; set; }
        public required string Version { get; set; }
        public bool Status { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public DateTime RemovedAt { get; set; }
    }
}

Models/TransactionRemark.cs
namespace smart_city_dotnetcore.Models
{
    public class TransactionRemark
    {
        public int Id { get; set; }
        public required string Title { get; set; }
        public required string Description { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}

Models/ViewModels/ErrorViewModel.cs
namespace smart_city_dotnetcore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AppUserController.cs
using Microsoft.AspNetCore.Mvc;
using smart_city_dotnetcore.Services;

namespace smart_city_dotnetcore.Controllers
{
    public class AppUserController : Controller
    {
        private readonly IAppUserService _appUserService;
        public AppUserController(IAppUserService appUserService)
        {
            _appUserService = appUserService;
        }
        public async Task<IActionResult> Index()
        {
            var users = await _appUserService.GetAll();
            return View(users);
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using smart_city_dotnetcore.Models;

namespace smart_city_dotnetcore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HouseController.cs
using Microsoft.AspNetCore.Mvc;
using smart_city_dotnetcore.Models;
using smart_city_dotnetcore.Services;

namespace smart_city_dotnetcore.Controllers
{
    public class HouseController : Controller
    {
        private readonly IHouseService _houseService;
        public HouseController(IHouseService houseService)
        {
            _houseService = houseService;
        }
        public async Task<IActionResult> Index()
        {
            var houses = await _houseService.GetAll();
            return View(houses);
        }
    }
}

Controllers/PowerMeterController.cs
using Microsoft.AspNetCore.Mvc;
using smart_city_dotnetcore.Services;

namespace smart_city_dotnetcore.Controllers
{
    public class PowerMeterController : Controller
    {
        private readonly IPowerMeterService _powerMeterService;
        public PowerMeterController(IPowerMeterService powerMeterService)
        {
            _powerMeterService = powerMeterService;
        }
        public async Task<IActionResult> Index()
        {
            var powerMeters = await _powerMeterService.GetAll();
            return View(powerMeters);
        }
    }
}

Views/AppUser/Index.cshtml
@model IEnumerable<smart_city_dotnetcore.Models.AppUser>

<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Middle Name</th>
            <th>Last Name</th>
            <th>Date Of Birth</th>
            <th>Gender</th>
            <th>Image</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var appUser in Model){
           <tr>
                <td>@appUser.FirstName</td>
                <td>@appUser.MiddleName</td>
                <td>@appUser.LastName</td>
                <td>@appUser.DateOfBirth</td>
                <td>@appUser.Gender</td>
                <td>@appUser.Image</td>
           </tr> 
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div> 
 

Views/House/Index.cshtml
@using Microsoft.CodeAnalysis.CSharp
@model IEnumerable<smart_city_dotnetcore.Models.House>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Address</th>
            <th>House No</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var house in Model)
        {
            <tr>
                <td>@house.Name</td>
                <td>@house.Description</td>
                <td>@house.Address</td>
                <td>@house.HouseNo</td>
            </tr>
        }
    </tbody>
</table>

Views/PowerMeter/Index.cshtml
@model IEnumerable<smart_city_dotnetcore.Models.PowerMeter>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>EntityId</th>
            <th>Type</th>
            <th>Phase</th>
            <th>Version</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var house in Model){
            <tr>
                <td>@house.Name</td>
                <td>@house.EntityId</td>
                <td>@house.Type</td>
                <td>@house.Phase</td>
                <td>@house.Version</td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Smart City</title> 
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/smart_city_dotnetcore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Smart City</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AppUser" asp-action="Index">App Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="Index">House</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PowerMeter" asp-action="Index">Power Meters</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - smart_city_dotnetcore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>